### ISSUE TITLE
Vue 2 template not working as expected with input fields

### ISSUE THREAD

**Issue by dwaynehulsman** [revolist/vue-datagrid#10]
I've been trying to make use of Vue Templates and ran into issues using Vue 2. When creating for example an input field in the template you're unable to focus on the element. See example: https://codesandbox.io/s/vue-select-type-forked-4yx9v?file=/src/App.vue (This is a fork of the vue 3 button example)

**Comment by revolist** [comment]
Check it here, it's working just fine:
https://codesandbox.io/s/revogrid-vuecomponent-forked-zdncx?file=/src/App.vue

**Comment by dwaynehulsman** [comment]
I just tested this in Chrome 89 (Windows 10) and I am unable to focus on the field meaning I won't be able to type any value into it.

https://user-images.githubusercontent.com/9630519/111120993-61e08b80-856c-11eb-8478-79b9c1fc91c8.mp4

**Comment by revolist** [comment]
@dwaynehulsman, have you been able to try on a sample I've provided?
there was a problem with the one you posted.

**Comment by dwaynehulsman** [comment]
The video you see above is from your sandbox, I am experiencing the exact same problem there like in my own.

**Comment by revolist** [comment]
Hey @dwaynehulsman,
We were able to reproduce this issue. The grid by itself treated as active area hence in order to use specific components not as editors but regular cells you need to drop default events but when you do so (preventDefault on input) you also dropping focus event, hence you have to return it back.

https://codesandbox.io/s/revogrid-vuecomponent-forked-zdncx?file=/src/App.vue
now sample should work.
