### ISSUE TITLE
Vue cell renderer bug

### ISSUE THREAD

**Issue by bbbford** [revolist/vue-datagrid#4]
Hi there, I'm writing a vue cell renderer to display boolean values as a switch. I'm finding that the display does not match the underlying data. Seems to only happen on scroll, perhaps something to do with the virtual dom renderer?

Simple repro here - [https://codesandbox.io/s/revogrid-vuecomponent-forked-ndxnc?file=/src/App.vue](https://codesandbox.io/s/revogrid-vuecomponent-forked-ndxnc?file=/src/App.vue)

Notice that only the first item in the list has a value of true, but when you scroll down it is displaying others as true.

**Comment by revolist** [comment]
Hello @bbbford 
This happens because of you are incorrectly using Vue renderer. 

It's not creating every single time when cell renders,  meaning `mounted` will be called only when component was rendered first time and DOM didn't changed. 

All you have to do is to make computed property or method.
Check it here:
https://codesandbox.io/s/revogrid-vuecomponent-cell-render-sample-63wmo?file=/src/App.vue
